---
- name: setup systemd for the nginx
  sudo: yes
  template: dest=/lib/systemd/system/nginx.service src=nginx_init backup=no

- name: change permission for nginx_init
  file: >
    path=/lib/systemd/system/nginx.service
    state=file
    mode=0640
    owner=root
    group=root

## Passenger 3 が nginx1.8のsrc install に対応していない
## passenger-install-nginx-module でsrc指定してもダメ
#
#- name: get nginx src
#  get_url: url={{ nginx_src_url }} dest=/tmp
#
#- name: unarchive {{ archive_ext }} for the nginx
#  unarchive: dest=/tmp/ src=/tmp/{{ nginx }}{{ archive_ext }} copy=no creates=yes
#
#- name: make Makefile for the nginx
#  sudo: no
#  command: >
#    chdir="/tmp/{{ nginx }}"
#    ./configure
#    --prefix={{ ngx_prefix }}
#    --conf-path={{ ngx_prefix }}/conf/nginx.conf
#    --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log
#    --http-client-body-temp-path=/var/lib/nginx/tmp/client_body
#    --http-proxy-temp-path=/var/lib/nginx/tmp/proxy
#    --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi
#    --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi
#    --http-scgi-temp-path=/var/lib/nginx/tmp/scgi
#    --pid-path=/var/run/nginx.pid
#    --lock-path=/run/lock/subsys/nginx
#    --user=nginx --group=nginx
#    --with-file-aio --with-ipv6
#    --with-http_ssl_module --with-http_spdy_module
#    --with-http_realip_module
#    --with-http_addition_module
#    --with-http_xslt_module
#    --with-http_image_filter_module
#    --with-http_geoip_module
#    --with-http_sub_module
#    --with-http_dav_module
#    --with-http_flv_module
#    --with-http_mp4_module
#    --with-http_gunzip_module
#    --with-http_gzip_static_module
#    --with-http_random_index_module
#    --with-http_secure_link_module
#    --with-http_degradation_module
#    --with-http_stub_status_module
#    --with-http_perl_module
#    --with-pcre
#    --with-google_perftools_module
#    --with-debug
#    --with-mail --with-mail_ssl_module
#    --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
##   --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
#    --add-module=/usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/passenger-3.0.21/ext/nginx
#
##--add-module=/var/www/gyazo/vendor/bundle/ruby/1.9.1/gems/passenger-3.0.21/ext/nginx
##  --add-module=/usr/local/rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/passenger-3.0.21/ext/nginx
#
#- name: build the nginx
#  sudo: yes
#  shell: >
#    make -j {{ ansible_processor_cores }} && \
#    make -j {{ ansible_processor_cores }} install
#    chdir=/tmp/{{ nginx }}

#- name: add group for nginx
#  group: name=nginx state=present system=#yes|no

- name: add user for nginx
  user: >
    name=nginx
    createhome=no
    state=present
    shell=/sbin/nologin

- name: add log dir for nginx
  file: >
    path=/var/log/nginx
    group=nginx
    state=directory
    mode=0755
    owner=nginx
