---
- name: check install nginx
  shell: systemctl is-active nginx
  register: result_nginx
  failed_when: False
  ignore_errors: True
  changed_when: False

- name: install nginx
  include: install_nginx.yml
  when: result_nginx.stdout in "unknown" or result_nginx.stdout in "failed"

- name: install module a nginx by passenger
  include: passenger-install-nginx.yml
  when: result_nginx.stdout in "unknown" or result_nginx.stdout in "failed"

- name: start nginx
  service: name=nginx state=started

- name: check listen web service
  shell: /sbin/ss -lan | grep :{{ port }}
  register: result_port
  changed_when: False

- name: check access url
  command: curl -I {{ url }}
  register: result_url_access
  changed_when: False

- name: Test gyazo web service
  assert:
    that:
      - result_port.rc == 0
      - result_url_access.rc == 0
