---
- hosts: all
  sudo: yes
  vars:
    - rbenv:
        env: 'system'
        version: 'v0.4.0'
        ruby_version: '1.9.3-p551'
  roles:
    - { role: zzet.rbenv, tags: 'setup_rbenv' }
    - { role: gyazo, tags: 'gyazo' }
    - { role: web, tags: 'web' }
